### ISSUE TITLE
Why does this happen?

### ISSUE THREAD

**Issue by ldx1u** [R-YaTian/TinkeDSi#3]
![00569641-CDA2-417B-8129-E7DB7AC09FD7](https://user-images.githubusercontent.com/114127384/191656079-43a07b52-853e-42a8-8689-eb1753c7b8da.jpeg)
Sometimes tinke likes to merge images and texture files together, thus creating this. Im making a mod for a game. How do i fix this?

**Comment by ZugPlayz** [comment]
eCDP

**Comment by R-YaTian** [comment]
Try to extract the single file, and open the file via TinkeDSi, I think auto merge image and texture files is not an issue actually.

**Comment by ldx1u** [comment]
1 year later... heh. Sadly the mod that im making has since been discontinued, because of this. Even though it was a feature. Can you tell me how to disable " auto merge image " please?

**Comment by R-YaTian** [comment]
> 1 year later... heh. Sadly the mod that im making has since been discontinued, because of this. Even though it was a feature. Can you tell me how to disable " auto merge image " please?

Will add an option to do it after merge changes for Image plugin from upstream in my spare time...

**Comment by R-YaTian** [comment]
> 1 year later... heh. Sadly the mod that im making has since been discontinued, because of this. Even though it was a feature. Can you tell me how to disable " auto merge image " please?

Hi, there. About this problem...This is mainly because: Tinke allows you to view Tile files, but you must load a palette first, otherwise Tinke will refuse to load the Tile files. This is the underlying logic of the Tinke Image plugin, and I am unlikely to redesign this underlying logic. Perhaps you could take a look at [NitroPaint](https://github.com/Garhoogin/NitroPaint), which is a great drawing tool for the Nintendo DS.
Closing ticket, sry for the long wait to reply...

**Comment by ldx1u** [comment]
I actually tried selecting palettes before and loading the image but it still didnt work.
